shortenedurl/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('urlprocessing.urls', namespace='base_urls')),
    # url(r'^admin/', include(admin.site.urls)),
]

urlprocessing/urls.py
from django.conf.urls import url

from .views import ShortenURLView, OriginalUrlView

urlpatterns = [
    url(r'^$', ShortenURLView.as_view(), name="add_url"),
    url(r'^(?P<hashval>[a-zA-Z0-9]+)$', OriginalUrlView.as_view(), name="get_url"),
]

urlprocessing/models.py
from django.db import models

class ShortenedUrl(models.Model):
	hash_url = models.URLField(max_length=200)
	original_url = models.URLField(max_length=512)
	date_created = models.DateTimeField(auto_now_add=True)
	date_updated = models.DateTimeField(auto_now=True)
	last_visited_date = models.DateField(blank=True, null=True, )

urlprocessing/forms.py
from django import forms
from django.forms import ModelForm
from urlprocessing.models import ShortenedUrl


class ShortenedUrlForm(ModelForm):
    # The picklist showing allowable groups to which a new list can be added
    # determines which groups the user belongs to. This queries the form object
    # to derive that list.
    def __init__(self, *args, **kwargs):
        super(ShortenedUrlForm, self).__init__(*args, **kwargs)

    class Meta:
        model = ShortenedUrl
        fields = ['original_url']

urlprocessing/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import View

from .forms import ShortenedUrlForm
from .models import ShortenedUrl
from .utils import StringShortener

class ShortenURLView(View):
	form_class = ShortenedUrlForm
	initial = {}
	template_name = 'urlprocessing/add_url.html'

	def get(self, request, *args, **kwargs):
		form = self.form_class(initial=self.initial)
		return render(request, self.template_name, {'form': form})

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST)
		if form.is_valid():
		    # <process form cleaned data>
		    existed_url = ShortenedUrl.objects.filter(original_url=form.cleaned_data['original_url'])
		    if existed_url.exists():
		    	return HttpResponse(existed_url[0].hash_url)
		    new_url = form.save()
		    new_url.hash_url = request.build_absolute_uri() + StringShortener().encode_url(n=new_url.id)
		    new_url.save()

		    return HttpResponse(new_url.hash_url)

		return render(request, self.template_name, locals())


class OriginalUrlView(View):
	def get(self, request, hashval, *args, **kwargs):
		try:
			url_to_redirect = ShortenedUrl.objects.get(hash_url__endswith=hashval)
			return redirect(url_to_redirect.original_url)
		except ShortenedUrl.DoesNotExist as e:
			return redirect('/')
		
		

urlprocessing/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %}URL Management{% endblock %}</title>
	<!--<script-->
  <!--src="https://code.jquery.com/jquery-3.2.1.min.js"-->
  <!--integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="-->
  <!--crossorigin="anonymous"></script>-->

  <script
  src="https://code.jquery.com/jquery-1.12.4.min.js"
  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
  crossorigin="anonymous"></script>

  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
  crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  {% block extrahead %} {% endblock %}
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">URL Management</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <div class="navbar-text">
              {% if request.user.is_authenticated %}
                Logged in as ({{ request.user.username }}) |
                <a href="{% url 'registration:auth_logout' %}">Logout</a>
              {% endif %}
          </div>
        </li>
        <!--<li>-->
          <!--<button type="button" class="btn btn-success btn-sm navbar-btn" data-toggle="modal" data-target="#myModal">Ask Question</button>-->
        <!--</li>-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
{% block content %}

{% endblock %}
</div>
</body>
</html>

urlprocessing/templates/urlprocessing/add_url.html
{% extends "urlprocessing/base.html" %}

{% block page_heading %}{% endblock %}
{% block title %}Shorten URL{% endblock %}

{% block content %}

	<h2>URL:</h2>

	<form action="" method="post" id="generateHash">
		{% csrf_token %}
	<table>{{ form }}</table>
	<p><input type="submit" value="Submit" class="todo-button"></p>
	</form>

	<p id="newUrl"></p>

	<script type="text/javascript">
		$('#generateHash').submit(function(){
			ret = false;
			console.log('Hello');
			$.ajax({
			  method: "POST",
			  url: "/",
			  data: { 
			  	original_url: $('#id_original_url').val(),
			  	csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
			  }
			})
			  .done(function( msg ) {
			    $('#newUrl').html(msg);
			    $('#id_original_url').val('')
			});
			return ret;
		})
	</script>

{% endblock %}

urlprocessing/templates/urlprocessing/base.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extrahead %}
	<!-- CSS and JavaScript for django-todo -->
	<link rel="stylesheet" type="text/css" href="{% static 'tasks/css/styles.css' %}" />
	<script src="{% static 'tasks/js/jquery.tablednd_0_5.js' %}" type="text/javascript"></script>
	<script type="text/javascript" charset="utf-8">
	    // thedate.x comes from the edit_task view. If this is a new entry,
	    // thedate won't be present and datepicker will fall back on the default (today).
	    $(document).ready(function(){
	        $('#id_due_date').datepicker();
	     });
	</script>
{% endblock extrahead %}

urlprocessing/templates/urlprocessing/del_list.html
{% extends "tasks/base.html" %}

{% block title %}{{ list.name }} Task{% endblock %}

{% block content %}

    {% if user.is_staff %}
        <h1>Delete task: {{ list.name }} ?</h1>


        <p> Are you sure you want to do that?</p>

        <form action="" method="post" accept-charset="utf-8">
		    {% csrf_token %}
            <input type="hidden" name="list" value="{{ list.id }}" id="some_name">
            <p><input type="submit" name="delete-confirm" value="Do it! &rarr;" class="todo-button"> </p>
        </form>

        <a href="{% url 'tasks:task-lists' %}">Return to Task: {{ list.name }}</a>

    {% else %}
        <p>Sorry, you don't have permission to delete lists. Please contact your group administrator.</p>
    {% endif %}

{% endblock %}

urlprocessing/templates/urlprocessing/lists.html
{% extends "tasks/base.html" %}

{% block title %}{{ list_title }} Task Lists{% endblock %}

{% block content %}

   <h1>Tasks Lists</h1>

    <ul>
        {% for task in task_list %}
	            <li><a href="{% url 'tasks:task_detail' task.id %}">{{ task.name }} </a></li>
        {% endfor %}
    </ul>

     <p><a href="add/">Create new task</a></p>

{% endblock %}

urlprocessing/templates/urlprocessing/view_task.html
{% extends "tasks/base.html" %}

{% block title %}Task: {{ task.name }}{% endblock %}

{% block content %}

    <script type="text/javascript">
        $(document).ready(function() {
            // Initially hide the TaskEdit form
            $('#TaskEdit').hide();
            // toggle slide to show the Add Task form when link clicked
            $('#slideToggle').click(function(){
                $(this).siblings('#TaskEdit').slideToggle();
            });
        });
    </script>

    {% if auth_ok %}

        <h2>{{ task }}</h2>

        <form action="" method="POST">
            {% csrf_token %}

            <p id="slideToggle" ><strong><a href="#"> &rarr; Click to edit details &larr; </a></strong></p>

            <p>
                <strong>Assigned to:</strong> {% if task.assigned_to %}{{ task.assigned_to.get_full_name }}{% else %}Anyone{% endif %}<br />
                <strong>Created by:</strong> {{ task.created_by.first_name }} {{ task.created_by.last_name }}<br />
                <strong>Due date:</strong>  {{ task.due_date }}<br />
                <strong>Completed:</strong> {{ form.completed }}<br />
            </p>

            {% if task.description %}
                <div class="task_note"><strong>Description:</strong> {{ task.description|safe|urlize|linebreaks }}</div>
            {% endif %}

            <div id="TaskEdit">
                <h3>Edit Task</h3>

                <table>
                    <tr>
                        <td>Title:</td>
                        <td>{{ form.name }}  </td>
                    </tr>

                    <tr>
                        <td>Due:</td>
                        <td>{{ form.due_date }}  </td>
                    </tr>

                    <tr>
                        <td>Assigned to:</td>
                        <td>{{ form.assigned_to }}  </td>
                    </tr>

                    <tr>
                        <td valign="top">Description:</td>
                        <td>{{ form.description }}  </td>
                    </tr>


                </table>
                <p><input type="submit" class="todo-button" name="edit_task" value="Edit task"></p>
            </div>


        </form>

        <a href="{% url 'tasks:task_delete' task.id %}">Delete Task</a> |
    {% endif %}
    <a href="{% url 'tasks:task-lists' %}">Task List</a>
{% endblock %}